---
hero_image: images / hemlighet-messages.png
theme: röd
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmering-1, phys-comp-0, tillverkning-0, community-0
title: Hemliga meddelanden
description: Gör ditt eget krypteringsprogram, för att skicka och ta emot hemliga meddelanden.
original_url: https://codeclubprojects.org/en-GB/python/secret-messages
interests: cyber-och-kryptografi
technologies: pytonorm
site_areas: projekt
hardware: ''
software: pytonorm
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: 'Introduktion: '
  - 
    title: Caesar cipher
  - 
    title: 'Utmaning: Använd en Caesar-chiffer'
  - 
    title: Kryptera bokstäver
  - 
    title: 'Utmaning: Variabelnycklar'
  - 
    title: Kryptera hela meddelanden
  - 
    title: Extra tecken
  - 
    title: 'Utmaning: Kryptering och dekryptering av meddelanden'
  - 
    title: 'Utmaning: Friendship Calculator'
